/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_peapad_avsdk_testndk_Test */

#ifndef _Included_cn_peapad_avsdk_testndk_Test
#define _Included_cn_peapad_avsdk_testndk_Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_peapad_avsdk_testndk_Test
 * Method:    helloC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_peapad_avsdk_testndk_Test_helloC
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
